Testing error on multiple commits.

diff --git a/.github/workflows/workflow-ci.yml b/.github/workflows/workflow-ci.yml
--- a/.github/workflows/workflow-ci.yml
+++ b/.github/workflows/workflow-ci.yml
@@ -22,5 +22,14 @@ jobs:
         compare_range=$(get_compare_range)
         paths=$(changed_paths_in_range "$compare_range")
         print_changed "$compare_range" "$paths"
-        build_images "$DOCKERHUB_ORG" "$paths"
+        docker_counter=`print_changed "$compare_range" "$paths" | grep -i "dockerfile" | wc -l`
+        if [ "${docker_counter}" -gt "1" ]; then
+          echo -e "ERROR: Currently we only support uploading one Dockerfile at a time, please break these into separate issues."
+          exit 1
+        elif [ "${docker_counter}" -eq "1" ]; then
+          echo "New or updated Dockerfile found, building image and running CI"
+          build_images "$DOCKERHUB_ORG" "$paths"
+        else
+          echo "No new images found, running CI only."
+        fi
         python3 tests/imagecheck.py "$DOCKERHUB_ORG" $paths
